version: '3.3'
services:
  dev:
    container_name: nestjs_process
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3003:3003
    networks:
      - nesjs-network
    # depends_on:
    #   - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  # mongodb:
  #   image : mongo:latest
  #   container_name: mongodb
  #   volumes:
  #     - ./database:/data/db
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - nesjs-network
  #   restart: always
networks:
  nesjs-network:
    external: true
    name: client_nesjs-network