version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        build:
            context: ./            
            # target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 8080/tcp
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
networks:
    nesjs-network: